version: '3.8'
services:

  elasticsearch:
    build:
      context: .
      dockerfile: BuildElasticSearch.dockerfile
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    networks:
      - elk_net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk_net

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      #- cloud.id=<Cloud ID from Elasticsearch Service>
      #- cloud.auth=elastic:<elastic password>
    networks:
      - elk_net

networks:
  elk_net: